# Generated by Django 5.0.1 on 2024-01-12 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0002_alter_lecturer_groups_alter_lecturer_subjects_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
