# Generated by Django 5.0.1 on 2024-01-31 18:33

import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0003_alter_lecturer_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtherMeasurableTypesControl',
            new_name='Student_Scores',
        ),
        migrations.RemoveField(
            model_name='overall_performance',
            name='measurable_types_control',
        ),
        migrations.AlterModelOptions(
            name='student_scores',
            options={'verbose_name': 'Баллы студента', 'verbose_name_plural': 'Баллы студентов'},
        ),
        migrations.RemoveField(
            model_name='overall_performance',
            name='other_measurable_types_control',
        ),
        migrations.AddField(
            model_name='overall_performance',
            name='student_scores',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='student_performance.student_scores', verbose_name='Баллы студентов'),
        ),
        migrations.DeleteModel(
            name='MeasurableTypesControl',
        ),
    ]
