# Generated by Django 5.0.1 on 2024-01-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0004_exam_grades_overall_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='overall_performance',
            name='overall_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Общее число баллов'),
        ),
    ]
