# Generated by Django 5.0.1 on 2024-02-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0004_rename_othermeasurabletypescontrol_student_scores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='term',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Семестр'),
        ),
    ]
