# Generated by Django 5.0.1 on 2024-03-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0006_alter_overall_performance_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='study_plan_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Учебный план'),
        ),
    ]
