# Generated by Django 5.0.1 on 2024-05-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0007_group_study_plan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_scores',
            name='points',
            field=models.CharField(max_length=2, verbose_name='Баллы/Пропуск'),
        ),
    ]
