# Generated by Django 5.0.1 on 2024-05-09 14:15

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0007_group_study_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='full_name',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat('first_name', 'last_name'), output_field=models.CharField(max_length=100, verbose_name='Поное имя')),
        ),
        migrations.AlterField(
            model_name='student_scores',
            name='points',
            field=models.CharField(default='0', max_length=2, verbose_name='Баллы/Пропуск'),
        ),
    ]
