# Generated by Django 5.0.1 on 2024-05-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0008_users_full_name_alter_student_scores_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='full_name',
        ),
    ]
