# Generated by Django 5.0.1 on 2024-05-09 15:46

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0009_remove_users_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='full_name',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat('first_name', models.Value(' '), 'last_name'), output_field=models.CharField(max_length=100, verbose_name='Поное имя')),
        ),
    ]
