# Generated by Django 5.0.1 on 2024-01-21 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_performance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Начало экзамена')),
                ('end_time', models.TimeField(verbose_name='Конец экзамена')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('classroom', models.CharField(blank=True, max_length=10, null=True, verbose_name='Аудитория')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_group', to='student_performance.group', verbose_name='Группа')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_lecturer', to='student_performance.lecturer', verbose_name='Преподаватель')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subject', to='student_performance.subject', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Экзамены',
            },
        ),
        migrations.CreateModel(
            name='TimetableChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.PositiveIntegerField(default=1, verbose_name='Номер пары')),
                ('start_time', models.TimeField(verbose_name='Начало пары')),
                ('end_time', models.TimeField(verbose_name='Конец пары')),
                ('day_of_the_week', models.CharField(max_length=15, verbose_name='День недели')),
                ('classroom', models.CharField(blank=True, max_length=10, null=True, verbose_name='Аудитория')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_group', to='student_performance.group', verbose_name='Группа')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes_lecturer', to='student_performance.lecturer', verbose_name='Преподаватель')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_subject', to='student_performance.subject', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Расписание замен',
                'verbose_name_plural': 'Расписание замен',
            },
        ),
        migrations.CreateModel(
            name='TimetableOfClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.PositiveIntegerField(default=1, verbose_name='Номер пары')),
                ('start_time', models.TimeField(verbose_name='Начало пары')),
                ('end_time', models.TimeField(verbose_name='Конец пары')),
                ('evenness', models.CharField(default='обе', max_length=10, verbose_name='Четность недели')),
                ('day_of_the_week', models.CharField(max_length=15, verbose_name='День недели')),
                ('classroom', models.CharField(blank=True, max_length=10, null=True, verbose_name='Аудитория')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_group', to='student_performance.group', verbose_name='Группа')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_lecturer', to='student_performance.lecturer', verbose_name='Преподаватель')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_subject', to='student_performance.subject', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Расписание занятий',
                'verbose_name_plural': 'Расписание занятий',
            },
        ),
    ]
