# Generated by Django 5.0.1 on 2024-01-13 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0003_delete_exam'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_group', to='student_performance.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_lecturer', to='student_performance.lecturer', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subject', to='student_performance.subject', verbose_name='Дисциплина'),
        ),
        migrations.CreateModel(
            name='TimetableChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.PositiveIntegerField(default=1, verbose_name='Номер пары')),
                ('start_time', models.TimeField(auto_now_add=True, verbose_name='Начало пары')),
                ('end_time', models.TimeField(verbose_name='Конец пары')),
                ('day_of_the_week', models.BooleanField(max_length=15, verbose_name='День недели')),
                ('classroom', models.CharField(blank=True, max_length=10, null=True, verbose_name='Аудитория')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_group', to='student_performance.group', verbose_name='Группа')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes_lecturer', to='student_performance.lecturer', verbose_name='Преподаватель')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_subject', to='student_performance.subject', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Расписание замен',
                'verbose_name_plural': 'Расписание замен',
            },
        ),
        migrations.CreateModel(
            name='TimetableOfClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.PositiveIntegerField(default=1, verbose_name='Номер пары')),
                ('start_time', models.TimeField(auto_now_add=True, verbose_name='Начало пары')),
                ('end_time', models.TimeField(verbose_name='Конец пары')),
                ('evenness', models.BooleanField(default=False, verbose_name='Четность недели')),
                ('day_of_the_week', models.BooleanField(max_length=15, verbose_name='День недели')),
                ('classroom', models.CharField(blank=True, max_length=10, null=True, verbose_name='Аудитория')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_group', to='student_performance.group', verbose_name='Группа')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_lecturer', to='student_performance.lecturer', verbose_name='Преподаватель')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_subject', to='student_performance.subject', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Расписание занятий',
                'verbose_name_plural': 'Расписание занятий',
            },
        ),
    ]
