# Generated by Django 5.0.1 on 2024-02-05 08:25

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.PositiveIntegerField(verbose_name='Номер аудитории')),
                ('floor', models.PositiveSmallIntegerField(verbose_name='Этаж')),
                ('number_of_seats', models.PositiveIntegerField(verbose_name='Количество посадочных мест')),
                ('number_of_computers', models.PositiveIntegerField(verbose_name='Количество компьютеров')),
                ('campus', models.PositiveSmallIntegerField(default=1, verbose_name='Номер корпуса')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=('floor', 'room_number'), unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
            },
        ),
    ]
