# Generated by Django 5.0.1 on 2024-01-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_exam_group_alter_exam_lecturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetablechanges',
            name='day_of_the_week',
            field=models.CharField(max_length=15, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='timetablechanges',
            name='start_time',
            field=models.TimeField(verbose_name='Начало пары'),
        ),
        migrations.AlterField(
            model_name='timetableofclasses',
            name='day_of_the_week',
            field=models.CharField(max_length=15, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='timetableofclasses',
            name='start_time',
            field=models.TimeField(verbose_name='Начало пары'),
        ),
    ]
