# Generated by Django 5.0.1 on 2024-01-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_alter_timetablechanges_day_of_the_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableofclasses',
            name='evenness',
            field=models.CharField(default='обе', max_length=10, verbose_name='Четность недели'),
        ),
    ]
