# Generated by Django 5.0.1 on 2024-02-15 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_work', '0001_initial'),
        ('timetable', '0005_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='student_work.quest', verbose_name='Задания'),
        ),
    ]
