# Generated by Django 5.0.1 on 2024-02-15 07:44

import django.db.models.deletion
import sortedm2m.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0005_users_term'),
        ('timetable', '0006_lesson_quest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='student_passes',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to=settings.AUTH_USER_MODEL, verbose_name='Пропуски'),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('number_of_lesson', models.PositiveIntegerField(verbose_name='Общее число пар')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_group', to='student_performance.group', verbose_name='Группа')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lecturer', to='student_performance.lecturer', verbose_name='Преподаватель')),
                ('lessons', sortedm2m.fields.SortedManyToManyField(help_text=None, to='timetable.lesson', verbose_name='Пары')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_subject', to='student_performance.subject', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журналы',
            },
        ),
    ]
