# Generated by Django 5.0.1 on 2024-02-16 10:48

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_alter_lesson_student_passes_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='get_url', unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='type_of_lesson',
            field=models.CharField(choices=[('пз', 'практическое занятие'), ('лк', 'лекционное занятие '), ('с', 'семинар')], default='лк', max_length=50, verbose_name='Тип занятия'),
        ),
    ]
