# Generated by Django 5.0.1 on 2024-02-17 15:21

import sortedm2m.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_journal_slug_lesson_type_of_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='lessons',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, null=True, to='timetable.lesson', verbose_name='Пары'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='type_of_lesson',
            field=models.CharField(choices=[('пз', 'практическое занятие'), ('лк', 'лекционное занятие'), ('с', 'семинар')], default='лк', max_length=50, verbose_name='Тип занятия'),
        ),
    ]
