# Generated by Django 5.0.1 on 2024-02-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_alter_journal_lessons_alter_lesson_type_of_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядковый номер пары'),
        ),
    ]
