# Generated by Django 5.0.1 on 2024-02-19 11:21

import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_alter_lesson_lesson_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='lessons',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='timetable.lesson', verbose_name='Пары'),
        ),
    ]
