# Generated by Django 5.0.1 on 2024-02-20 18:23

import sortedm2m.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_alter_journal_lessons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='student_passes',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to=settings.AUTH_USER_MODEL, verbose_name='Пропуски'),
        ),
    ]
