# Generated by Django 5.0.1 on 2024-02-22 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0006_alter_overall_performance_subject_and_more'),
        ('student_work', '0002_alter_quest_lecturer_alter_userquest_quest'),
        ('timetable', '0012_alter_lesson_student_passes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.classroom', verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_lecturer', to='student_performance.lecturer', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.classroom', verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_lecturer', to='student_performance.lecturer', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_work.quest', verbose_name='Задания'),
        ),
        migrations.AlterField(
            model_name='timetablechanges',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.classroom', verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='timetablechanges',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_lecturer', to='student_performance.lecturer', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='timetableofclasses',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.classroom', verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='timetableofclasses',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_lecturer', to='student_performance.lecturer', verbose_name='Преподаватель'),
        ),
    ]
