# Generated by Django 4.2.10 on 2024-03-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_alter_exam_classroom_alter_exam_lecturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableofclasses',
            name='day_of_the_week',
            field=models.CharField(choices=[('понедельник', 'понедельник'), ('вторник', 'вторник'), ('среда', 'среда'), ('четверг', 'четверг'), ('пятница', 'пятница'), ('суббота', 'суббота')], max_length=30, verbose_name='День недели'),
        ),
    ]
