# Generated by Django 5.0.1 on 2024-03-12 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0006_alter_overall_performance_subject_and_more'),
        ('timetable', '0014_alter_timetableofclasses_day_of_the_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonWorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100, verbose_name='Причина')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Не рабочий день',
                'verbose_name_plural': 'Не рабочие дни',
            },
        ),
        migrations.CreateModel(
            name='PracticeTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название практики')),
                ('start_date', models.DateField(verbose_name='Дата начала практики')),
                ('end_date', models.DateField(verbose_name='Дата конца практики')),
                ('industrial_practice', models.BooleanField(default=False, verbose_name='Производственная практика')),
                ('document', models.FileField(blank=True, null=True, upload_to='accompanying_document/%Y/%m/%d/', verbose_name='Сопроводительный документ')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_group', to='student_performance.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Практика',
                'verbose_name_plural': 'Практики',
            },
        ),
    ]
