# Generated by Django 5.0.1 on 2024-03-28 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0006_alter_overall_performance_subject_and_more'),
        ('timetable', '0015_nonworkingday_practicetimetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(db_index=True, max_length=200, verbose_name='Название учебного плана')),
                ('term', models.PositiveSmallIntegerField(default=1, verbose_name='Семестр')),
                ('number_of_hours', models.PositiveIntegerField(verbose_name='Количество часов')),
                ('last_work', models.CharField(choices=[('Не предусмотрено', 'Не предусмотрено'), ('Экзамен', 'Экзамен'), ('Зачет', 'Зачет')], default='Не предусмотрено', max_length=50, verbose_name='Экзамен/Зачет')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plan_subject', to='student_performance.subject', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Учебный план',
                'verbose_name_plural': 'Учебные планы',
            },
        ),
    ]
