# Generated by Django 5.0.1 on 2024-05-09 14:15

import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0008_users_full_name_alter_student_scores_points'),
        ('timetable', '0016_study_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='student_passes',
        ),
        migrations.AddField(
            model_name='lesson',
            name='student_scores',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='student_performance.student_scores', verbose_name='Баллы'),
        ),
    ]
