# Generated by Django 5.0.1 on 2024-05-02 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0016_study_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='student_passes',
        ),
    ]
