# Generated by Django 5.0.1 on 2024-02-22 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_performance', '0006_alter_overall_performance_subject_and_more'),
        ('student_work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_lecturer', to='student_performance.lecturer', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='userquest',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_work.quest', verbose_name='Задание'),
        ),
    ]
